name:                hello-haskell
version:             0.1.0.0
license:             BSD3
author:              "Shane Kenney"
maintainer:          "example@example.com"

extra-source-files:
- README.md

description:         Haskell serverless using AWS Lambda

dependencies:
- base >= 4.7 && < 5
- serverless-haskell
- aeson
- text
- lens
- bytestring

executables:
  app:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
