service: hellohaskell

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  hello:
    # Here, mypackage is the Haskell package name and myfunc is the executable
    # name as defined in the Cabal file
    handler: hello-haskell.app
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-haskell