service: hellohaskell

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  hello:
    handler: hello-haskell.app
    # Here, mypackage is the Haskell package name and myfunc is the executable
    # name as defined in the Cabal file

plugins:
  - serverless-haskell